### ISSUE TITLE
Resource leaks in libiconv 1.16

### ISSUE THREAD

**Issue by noloader** [fumiyas/libiconv-utf8mac#1]
Hi Everyone,

Thanks for the port with UTF-8-Mac. I think I may need to switch to it (and move away from the crippled GNU version).

You might consider adding this patch to your version of libiconv: [Noloader | libiconv.patch](https://github.com/noloader/Build-Scripts/blob/master/patch/iconv.patch). It cleans up resource leaks in libiconv so the library can get through acceptance testing and security testing and evaluation (ST&E).

Without the patch, both libiconv and programs that depend upon iconv fail to get through testing.

-----

Applying the patch should be as simple as the following:

```
$ git clone ...
$ cd libiconv-utf8mac/
$ git checkout utf-8-mac-51.200.6.libiconv-1.16
$ wget https://raw.githubusercontent.com/noloader/Build-Scripts/master/patch/iconv.patch
$ patch -p0 < iconv.patch
```

**Comment by fumiyas** [comment]
https://github.com/noloader/Build-Scripts/blob/master/patch/iconv.patch.old

This patch is not required. All allocated resources are freed by the kernel on terminating a process.

**Comment by noloader** [comment]
> This patch is not required.

Not true for two reasons.

First, It is reported as a memory leak by analysis tools. The memory leak subsequently breaks the program that is trying to run because some memory checkers abort on the first leak.

It is so bad on GNU systems that I cannot run basic tools and get through testing. libiconv fails, ncurses fails, bash fails, make fails. Scripts and programs stop working because of the aborts during testing.

In fact, because so many programs depend on libiconv and gettext, Autotools configuration fails so we can never move on to actually building tools like bash and make. The packages fail to configure.

Second, managed languages, like Java and .Net, load and unload shared objects multiple times during the course of program execution. The memory leaks accumulate over the lifetime of the program.

Android phones really suffer (2). Android apps using JNI often suffer resource exhaustion because libraries like libiconv, ncurses and OpenSSL are so sloppy with their cleanup.
