### ISSUE TITLE
No rule to make target 'build-aux/compile', needed by 'distdir'

### ISSUE THREAD

**Issue by noloader** [fumiyas/libiconv-utf8mac#4]
Hi Everyone,

I'm trying to build a new tarball according to the README. Most goes well, but the end of `make -f Makefile.utf8mac dist` fails with:

```
rm -rf $tmpdistdir $tmpdistdir.tar $tmpdistdir.tar.gz \
  && mkdir $tmpdistdir \
  && make distdir distdir="$abstmpdistdir" \
  && tar chof $tmpdistdir.tar --owner=root --group=root $tmpdistdir \
  && gzip -9 $tmpdistdir.tar \
  && rm -rf $tmpdistdir
make[2]: Entering directory '/home/jwalton/libiconv-utf8mac/libiconv'
make[2]: *** No rule to make target 'build-aux/compile', needed by 'distdir'.  Stop.
make[2]: Leaving directory '/home/jwalton/libiconv-utf8mac/libiconv'
Makefile:241: recipe for target 'dist' failed
make[1]: *** [dist] Error 2
make[1]: Leaving directory '/home/jwalton/libiconv-utf8mac/libiconv'
Makefile.utf8mac:24: recipe for target 'dist' failed
```

I'm experiencing the problem on both Fedora and Ubuntu. Looking at `build-aux`, there is `ltmain.sh` and `mkinstalldirs`, but there is no `compile`.

The best I can tell the only difference between our repos are the fixes for the memory leaks.

**Comment by fumiyas** [comment]
Are you using GNU automake 1.16.x, GNU autoconf 2.69 and other requirements?

https://git.savannah.gnu.org/gitweb/?p=libiconv.git;a=blob;f=HACKING;h=193a844319c25b5a6d2ab3cf26091d9555b7c600;hb=HEAD#l5

**Comment by fumiyas** [comment]
I can reproduce the same (similar?) problem on Ubuntu 18.04 (GNU automake  1:1.15.1-3ubuntu2).
